global:
  scrape_interval:     30s # El intervalo en el que se traerá las métricas
  evaluation_interval: 30s # Evaluará las reglas cada 30 segundos, por defecto es cada minuto

scrape_configs:

  - job_name: 'servers-dev'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:
      # ------------------------------------- #
      - targets: [ '192.168.0.101:9090']  # DEV
        labels:
          pais: AR
          entorno: DEV
          cliente: cliente
          hostname: dev-cliente-ar
      # ------------------------------------- #
      - targets: [ '192.168.0.102:9090']  # QA
        labels:
          pais: AR
          entorno: QA
          cliente: cliente
          hostname: qa-cliente-ar
      # ------------------------------------- #
      - targets: [ '192.168.0.103:9090']  # QA2
        labels:
          pais: AR
          entorno: QA2
          cliente: cliente
          hostname: qa2-cliente-ar
      # ------------------------------------- #
      
